import json
import os

notebook_path = r'd:\銘澄專區\畢業專題工作區\讀取訓練結果.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

target_keyword = "# 分析多個訓練結果，找出最佳模型的效能指標與參數"
target_cell = None
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and any(target_keyword in line for line in cell['source']):
        target_cell = cell
        break

if target_cell:
    # 這裡我將優化 duration_str 的計算邏輯，優先使用 results.csv 中的 time 欄位
    new_source = [
        "# 分析多個訓練結果，找出最佳模型的效能指標與參數\n",
        "import sys\n",
        "import os\n",
        "import pandas as pd\n",
        "import yaml\n",
        "import datetime\n",
        "from glob import glob\n",
        "\n",
        "sys.argv = [sys.argv[0]]\n",
        "try:\n",
        "    if 'ROOT_DIR' not in locals():\n",
        "        ROOT_DIR = 'runs\\\\detect'\n",
        "except NameError:\n",
        "    ROOT_DIR = 'runs\\\\detect'\n",
        "\n",
        "def get_data_count(data_yaml_path):\n",
        "    \"\"\"從 data.yaml 獲取訓練集圖片數量，增強路徑自癒能力\"\"\"\n",
        "    if not data_yaml_path:\n",
        "        return \"N/A\"\n",
        "    \n",
        "    current_workspace = os.getcwd()\n",
        "    if not os.path.exists(data_yaml_path):\n",
        "        potential_names = ['strawberry-maturity-yolo-graduate-1', 'yolo_data', 'roboflow_側拍']\n",
        "        for name in potential_names:\n",
        "            if name in data_yaml_path:\n",
        "                alt_path = os.path.join(current_workspace, name, 'data.yaml')\n",
        "                if os.path.exists(alt_path):\n",
        "                    data_yaml_path = alt_path\n",
        "                    break\n",
        "    \n",
        "    if not os.path.exists(data_yaml_path):\n",
        "        basename = os.path.basename(data_yaml_path)\n",
        "        if os.path.exists(basename):\n",
        "            data_yaml_path = basename\n",
        "\n",
        "    if not os.path.exists(data_yaml_path):\n",
        "        return \"N/A\"\n",
        "        \n",
        "    try:\n",
        "        with open(data_yaml_path, 'r', encoding='utf-8') as f:\n",
        "            d_yaml = yaml.safe_load(f)\n",
        "            yaml_dir = os.path.dirname(os.path.abspath(data_yaml_path))\n",
        "            base_path = d_yaml.get('path', '')\n",
        "            train_rel = d_yaml.get('train', '')\n",
        "            \n",
        "            if os.path.isabs(train_rel):\n",
        "                full_path = train_rel\n",
        "            elif base_path:\n",
        "                if os.path.isabs(base_path):\n",
        "                    if not os.path.exists(base_path):\n",
        "                        folder_name = os.path.basename(base_path)\n",
        "                        full_path = os.path.join(current_workspace, folder_name, train_rel)\n",
        "                    else:\n",
        "                        full_path = os.path.join(base_path, train_rel)\n",
        "                else:\n",
        "                    full_path = os.path.join(yaml_dir, base_path, train_rel)\n",
        "            else:\n",
        "                full_path = os.path.join(yaml_dir, train_rel)\n",
        "            \n",
        "            full_path = os.path.normpath(full_path)\n",
        "            \n",
        "            if not os.path.exists(full_path):\n",
        "                clean_rel = train_rel.replace('../', '').replace('./', '')\n",
        "                alt_full_path = os.path.join(yaml_dir, clean_rel)\n",
        "                if os.path.exists(alt_full_path):\n",
        "                    full_path = alt_full_path\n",
        "\n",
        "            if os.path.exists(full_path):\n",
        "                imgs = [f for f in os.listdir(full_path) if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]\n",
        "                return len(imgs)\n",
        "    except:\n",
        "        pass\n",
        "    return \"N/A\"\n",
        "\n",
        "def format_duration(seconds):\n",
        "    \"\"\"將秒數轉為易讀格式\"\"\"\n",
        "    if seconds <= 0: return \"< 1m\"\n",
        "    h = int(seconds // 3600)\n",
        "    m = int((seconds % 3600) // 60)\n",
        "    if h > 0: return f\"{h}h {m}m\"\n",
        "    return f\"{m}m\"\n",
        "\n",
        "def compare_training_results():\n",
        "    \"\"\"\n",
        "    從各訓練目錄提取效能、參數、日期、時長與資料量進行排名\n",
        "    \"\"\"\n",
        "    print(f\"🔍 正在掃描 {ROOT_DIR} 下的所有訓練紀錄...\\\\n\")\n",
        "    \n",
        "    summary_data = []\n",
        "    search_path = os.path.join(ROOT_DIR, '*')\n",
        "    folders = glob(search_path)\n",
        "    \n",
        "    if not folders:\n",
        "        print(\"❌ 找不到任何訓練資料夾，請確認路徑是否正確。\")\n",
        "        return\n",
        "\n",
        "    for folder in folders:\n",
        "        if not os.path.isdir(folder): continue\n",
        "        \n",
        "        csv_path = os.path.join(folder, 'results.csv')\n",
        "        args_path = os.path.join(folder, 'args.yaml')\n",
        "        \n",
        "        # 1. 基礎資訊：日期與初步時長預估 (檔案修改時間)\n",
        "        train_date = \"N/A\"\n",
        "        mtime_duration = 0\n",
        "        if os.path.exists(args_path):\n",
        "            t_start = os.path.getmtime(args_path)\n",
        "            train_date = datetime.datetime.fromtimestamp(t_start).strftime('%Y-%m-%d')\n",
        "            if os.path.exists(csv_path):\n",
        "                t_end = os.path.getmtime(csv_path)\n",
        "                mtime_duration = t_end - t_start\n",
        "        \n",
        "        if os.path.exists(csv_path):\n",
        "            try:\n",
        "                # 2. 讀取結果與參數\n",
        "                df = pd.read_csv(csv_path)\n",
        "                df.columns = [c.strip() for c in df.columns]\n",
        "                \n",
        "                # 優先使用 results.csv 中的 'time' 欄位 (這是實際訓練秒數)\n",
        "                if 'time' in df.columns and not df['time'].isnull().all():\n",
        "                    total_seconds = df['time'].iloc[-1]\n",
        "                    duration_str = format_duration(total_seconds)\n",
        "                else:\n",
        "                    # 退而求其次使用檔案修改時間差\n",
        "                    duration_str = format_duration(mtime_duration)\n",
        "                \n",
        "                map_cols = [c for c in df.columns if 'mAP50-95' in c]\n",
        "                target_col = map_cols[0] if map_cols else None\n",
        "                \n",
        "                if target_col and not df[target_col].isnull().all():\n",
        "                    best_idx = df[target_col].idxmax()\n",
        "                    best_row = df.iloc[best_idx]\n",
        "                    \n",
        "                    params = {}\n",
        "                    data_count = \"N/A\"\n",
        "                    if os.path.exists(args_path):\n",
        "                        with open(args_path, 'r', encoding='utf-8') as f:\n",
        "                            args_data = yaml.safe_load(f)\n",
        "                            params['Model'] = args_data.get('model', 'Unknown')\n",
        "                            params['Total_Epochs'] = args_data.get('epochs', 0)\n",
        "                            params['Patience'] = args_data.get('patience', 0)\n",
        "                            params['Optimizer'] = args_data.get('optimizer', 'auto')\n",
        "                            params['Batch'] = args_data.get('batch', 0)\n",
        "                            data_count = get_data_count(args_data.get('data'))\n",
        "                    else:\n",
        "                        params = {'Model': 'N/A', 'Total_Epochs': 'N/A', 'Patience': 'N/A', 'Optimizer': 'N/A', 'Batch': 'N/A'}\n",
        "\n",
        "                    folder_name = os.path.basename(folder)\n",
        "                    summary_data.append({\n",
        "                        '資料夾': folder_name,\n",
        "                        '日期': train_date,\n",
        "                        '時長': duration_str,\n",
        "                        '資料量': data_count,\n",
        "                        '模型': params['Model'],\n",
        "                        '優化器': params['Optimizer'],\n",
        "                        'Batch': params['Batch'],\n",
        "                        '總回合': params['Total_Epochs'],\n",
        "                        '實際回合': len(df),\n",
        "                        '早停': params['Patience'],\n",
        "                        'mAP50-95': best_row[target_col],\n",
        "                        'mAP50': best_row.get('metrics/mAP50(B)', best_row.get('metrics/mAP50', 0)),\n",
        "                        'Precision': best_row.get('metrics/precision(B)', best_row.get('metrics/precision', 0)),\n",
        "                        'Recall': best_row.get('metrics/recall(B)', best_row.get('metrics/recall', 0))\n",
        "                    })\n",
        "            except Exception as e:\n",
        "                print(f\"⚠️ 無法讀取 {folder}: {e}\")\n",
        "\n",
        "    if summary_data:\n",
        "        result_df = pd.DataFrame(summary_data)\n",
        "        result_df = result_df.sort_values(by='mAP50-95', ascending=False).reset_index(drop=True)\n",
        "        \n",
        "        print(\"=\" * 140)\n",
        "        print(\"🏆 訓練效能與參數總和排行榜 (依照 mAP50-95 排序)\")\n",
        "        print(\"=\" * 140)\n",
        "        try: print(result_df.to_markdown(index=False, numalign='left', stralign='left'))\n",
        "        except: print(result_df.to_string(index=False))\n",
        "        print(\"=\" * 140)\n",
        "        \n",
        "        best_run = result_df.iloc[0]\n",
        "        print(f\"\\\\n🥇 表現最優異訓練: {best_run['資料夾']} (資料量: {best_run['資料量']}, 時長: {best_run['時長']})\")\n",
        "        print(f\"   模型版本: {best_run['模型']} | 優化器: {best_run['優化器']} | Batch: {best_run['Batch']}\")\n",
        "        print(f\"   最終指標 -> mAP50-95: {best_run['mAP50-95']:.4f}, mAP50: {best_run['mAP50']:.4f}\")\n",
        "        print(f\"\\\\n💡 推薦使用此權重進行部署: runs/detect/{best_run['資料夾']}/weights/best.pt\")\n",
        "    else:\n",
        "        print(\"❌ 未發現有效的結果數據。\")\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    compare_training_results()\n"
    ]
    target_cell['source'] = new_source

    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Notebook updated successfully with time column logic.")
else:
    print("Target cell not found.")
