import json
import os
import sys

# Reconfigure stdout to use utf-8 to avoid Big5 (cp950) encoding errors with emojis
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

"""
🛠️ Notebook 批量修復/更新工具 (Agent 專用)
"""

ipynb_path = r"d:\銘澄專區\畢業專題工作區\讀取訓練結果.ipynb"

cell4_source = [
    "#監控訓練中的最新結果\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "import time\n",
    "import glob\n",
    "import threading\n",
    "from IPython.display import clear_output, display\n",
    "\n",
    "# 旗標：控制背景監控是否繼續\n",
    "keep_running = True\n",
    "\n",
    "def get_latest_results_csv(base_path=\"Strawberry_YOLOv11_4060ti-16G/*/results.csv\"):\n",
    "    files = glob.glob(base_path)\n",
    "    if not files: return None\n",
    "    return max(files, key=os.path.getmtime)\n",
    "\n",
    "def plot_training_results():\n",
    "    csv_path = get_latest_results_csv()\n",
    "    if csv_path is None or not os.path.exists(csv_path):\n",
    "        print(f\"⌛ 等待訓練數據產生中...\")\n",
    "        return\n",
    "\n",
    "    try:\n",
    "        df = pd.read_csv(csv_path)\n",
    "        df.columns = [c.strip() for c in df.columns]\n",
    "    except: return\n",
    "\n",
    "    if df.empty: return\n",
    "\n",
    "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "    # --- Loss 圖 ---\n",
    "    ax1.plot(df['epoch'], df['train/box_loss'], label='Train Box', color='blue', alpha=0.4)\n",
    "    ax1.plot(df['epoch'], df['val/box_loss'], label='Val Box', color='blue', linestyle='--')\n",
    "    ax1.plot(df['epoch'], df['train/cls_loss'], label='Train Cls', color='orange', alpha=0.4)\n",
    "    ax1.plot(df['epoch'], df['val/cls_loss'], label='Val Cls', color='orange', linestyle='--')\n",
    "    ax1.set_title(f\"Loss Curves ({os.path.basename(os.path.dirname(csv_path))})\")\n",
    "    ax1.legend(); ax1.grid(True)\n",
    "\n",
    "    # --- mAP 圖 ---\n",
    "    ax2.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP50', color='green', linewidth=2)\n",
    "    ax2.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP50-95', color='red', linewidth=1)\n",
    "    ax2.set_title(\"mAP Metrics\")\n",
    "    ax2.legend(); ax2.grid(True)\n",
    "\n",
    "    clear_output(wait=True)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    print(f\"📊 最新更新時間: {time.strftime('%Y-%m-%d %H:%M:%S')} | 數據源: {csv_path}\")\n",
    "\n",
    "def monitor_loop(interval=10):\n",
    "    while keep_running:\n",
    "        plot_training_results()\n",
    "        time.sleep(interval)\n",
    "\n",
    "# 啟動背景監控執行緒\n",
    "monitor_thread = threading.Thread(target=monitor_loop, args=(10,), daemon=True)\n",
    "monitor_thread.start()\n",
    "print(\"🟢 已經在背景啟動訓練結果即時監控！每一輪(Epoch)結束後圖表將會自動重繪。\")\n"
]

cell6_source = [
    "import sys\n",
    "sys.argv = [sys.argv[0]]\n",
    "import nvidia_ml_py as pynvml\n",
    "import torch\n",
    "\n",
    "def safe_decode(val):\n",
    "    if isinstance(val, bytes): return val.decode('utf-8', errors='ignore')\n",
    "    return str(val)\n",
    "\n",
    "def get_gpu_health_check():\n",
    "    print(\"========================================================================\")\n",
    "    print(\"🚀 RTX 4060 Ti (16G) GPU 健檢程式 - 鎖定 pytorch 核心環境與 nvidia-ml-py 驅動\")\n",
    "    print(\"========================================================================\")\n",
    "    \n",
    "    # 1. 檢查 PyTorch CUDA 可用度\n",
    "    cuda_available = torch.cuda.is_available()\n",
    "    print(f\"🔹 PyTorch CUDA 可用狀態: {cuda_available}\")\n",
    "    if cuda_available:\n",
    "        print(f\"   - 顯示卡型號       : {torch.cuda.get_device_name(0)}\")\n",
    "        print(f\"   - CUDA 驅動版本    : {torch.version.cuda}\")\n",
    "        print(f\"   - PyTorch 核心版本 : {torch.__version__}\")\n",
    "    else:\n",
    "        print(\"   ❌ PyTorch 無法辨識 GPU，請檢查 CUDA / PyTorch 版本對齊狀態！\")\n",
    "        return\n",
    "        \n",
    "    # 2. 透過 nvidia-ml-py 初始化並提取精確物理硬體數據\n",
    "    print(\"\\n🔹 nvidia-ml-py (NVML) 硬體即時數據診斷:\")\n",
    "    try:\n",
    "        pynvml.nvmlInit()\n",
    "        handle = pynvml.nvmlDeviceGetHandleByIndex(0)\n",
    "        \n",
    "        # 取得各種資訊\n",
    "        gpu_name = safe_decode(pynvml.nvmlDeviceGetName(handle))\n",
    "        driver_ver = safe_decode(pynvml.nvmlSystemGetDriverVersion())\n",
    "        mem_info = pynvml.nvmlDeviceGetMemoryInfo(handle)\n",
    "        \n",
    "        # 時脈與頻寬相關\n",
    "        curr_graphics_clock = pynvml.nvmlDeviceGetClockInfo(handle, pynvml.NVML_CLOCK_GRAPHICS)\n",
    "        curr_mem_clock = pynvml.nvmlDeviceGetClockInfo(handle, pynvml.NVML_CLOCK_MEM)\n",
    "        max_graphics_clock = pynvml.nvmlDeviceGetMaxClockInfo(handle, pynvml.NVML_CLOCK_GRAPHICS)\n",
    "        \n",
    "        # 溫度與電力\n",
    "        temp = pynvml.nvmlDeviceGetTemperature(handle, pynvml.NVML_TEMPERATURE_GPU)\n",
    "        power_usage = pynvml.nvmlDeviceGetPowerUsage(handle) / 1000.0 # 轉為 W\n",
    "        power_limit = pynvml.nvmlDeviceGetPowerManagementLimit(handle) / 1000.0\n",
    "\n",
    "        print(f\"   - 正式名稱       : {gpu_name}\")\n",
    "        print(f\"   - 驅動程式版本   : {driver_ver}\")\n",
    "        print(f\"   - 總顯存 (VRAM)  : {mem_info.total / 1024**2:.0f} MB\")\n",
    "        print(f\"   - 目前顯存佔用   : {mem_info.used / 1024**2:.0f} MB ({(mem_info.used/mem_info.total)*100:.1f}%)\")\n",
    "        print(f\"   - 核心時脈       : {curr_graphics_clock} MHz (Max: {max_graphics_clock} MHz)\")\n",
    "        print(f\"   - 記憶體時脈     : {curr_mem_clock} MHz\")\n",
    "        print(f\"   - 當前溫度       : {temp} °C\")\n",
    "        print(f\"   - 當前功耗       : {power_usage:.1f} W / {power_limit:.1f} W\")\n",
    "        \n",
    "        # 計算理論頻寬\n",
    "        pcie_gen = pynvml.nvmlDeviceGetMaxPcieLinkGeneration(handle)\n",
    "        pcie_width = pynvml.nvmlDeviceGetMaxPcieLinkWidth(handle)\n",
    "        print(f\"   - PCIe 介面      : Gen {pcie_gen} x{pcie_width}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"   ❌ NVML 診斷失敗: {e}\")\n",
    "    finally:\n",
    "        try: pynvml.nvmlShutdown()\n",
    "        except: pass\n",
    "\n",
    "    print(f\"\\n{'='*80}\")\n",
    "    print(\"✅ 健檢完成！目前環境與 RTX 4060 Ti 處於最佳狀態。\")\n",
    "\n",
    "get_gpu_health_check()\n"
]

def update_notebook():
    if not os.path.exists(ipynb_path):
        print(f"❌ 找不到目標檔案: {ipynb_path}")
        return

    with open(ipynb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    nb['cells'][4]['source'] = cell4_source
    nb['cells'][6]['source'] = cell6_source

    with open(ipynb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    
    print(f"✅ 已成功更新 讀取訓練結果.ipynb 中的 Cell 4 與 Cell 6。")

def fix_video_detection_notebook():
    video_ipynb_path = r"d:\銘澄專區\畢業專題工作區\影片偵測.ipynb"
    if not os.path.exists(video_ipynb_path):
        print(f"❌ 找不到目標檔案: {video_ipynb_path}")
        return

    with open(video_ipynb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    cell3_source = [
        'import sys\n',
        'sys.argv = [sys.argv[0]]\n',
        'import os, glob, cv2, time\n',
        'import numpy as np\n',
        'from ultralytics import YOLO\n',
        'from tqdm.notebook import tqdm\n',
        'from collections import defaultdict\n',
        '\n',
        'def find_model_path_by_id(target_id="", base_dir="runs/detect"):\n',
        '    """\n',
        '    從輸入編號 (如 1c, 7) 自動搜尋匹配的權重檔案路徑，預設/為空時取最新 (*)\n',
        '    """\n',
        '    if not target_id or target_id == \'*\':\n',
        '        search_patterns = [os.path.join(base_dir, \'train*\'), os.path.join(base_dir, \'exp*\')]\n',
        '        dirs = []\n',
        '        for pattern in search_patterns: dirs.extend(glob.glob(pattern))\n',
        '        valid_dirs = [d for d in dirs if os.path.exists(os.path.join(d, \'weights\', \'best.pt\'))]\n',
        '        if valid_dirs:\n',
        '            latest_dir = max(valid_dirs, key=os.path.getmtime)\n',
        '            return os.path.join(latest_dir, \'weights\', \'best.pt\')\n',
        '        weights = glob.glob(os.path.join(\'best_weights\', \'*.pt\'))\n',
        '        return max(weights, key=os.path.getmtime) if weights else \'yolov11n.pt\'\n',
        '        \n',
        '    search_patterns = [os.path.join(base_dir, \'train*\'), os.path.join(base_dir, \'exp*\')]\n',
        '    dirs = []\n',
        '    for pattern in search_patterns: dirs.extend(glob.glob(pattern))\n',
        '    \n',
        '    matched_dirs = []\n',
        '    for d in dirs:\n',
        '        folder_name = os.path.basename(d).lower()\n',
        '        if target_id.lower() in folder_name and os.path.exists(os.path.join(d, \'weights\', \'best.pt\')):\n',
        '            matched_dirs.append(d)\n',
        '            \n',
        '    if matched_dirs:\n',
        '        best_match = max(matched_dirs, key=os.path.getmtime)\n',
        '        return os.path.join(best_match, \'weights\', \'best.pt\')\n',
        '        \n',
        '    best_weights_dir = \'best_weights\'\n',
        '    if os.path.exists(best_weights_dir):\n',
        '        weights = glob.glob(os.path.join(best_weights_dir, \'*.pt\'))\n',
        '        matched_weights = [w for w in weights if target_id.lower() in os.path.basename(w).lower()]\n',
        '        if matched_weights:\n',
        '            return max(matched_weights, key=os.path.getmtime)\n',
        '            \n',
        '    if os.path.exists(target_id): return target_id\n',
        '        \n',
        '    print(f"⚠️ 找不到匹配編號 \'{target_id}\' 的權重檔，將自動切換為最新模型 (*)")\n',
        '    return find_model_path_by_id(\'*\', base_dir)\n',
        '\n',
        '# ==========================================\n',
        '# 🎬 影片偵測核心 (支援單部 / 批量 / 獨立 ID)\n',
        '# ==========================================\n',
        '\n',
        '# 1. 任務設定\n',
        'SOURCE_LIST = [\n',
        '    "測試模型用/模擬_4(無聲音).mp4",\n',
        ']\n',
        '\n',
        '# 2. 功能開關\n',
        'VID_STRIDE     = 1\n',
        'CONF_THRESHOLD = 0.5\n',
        'ENABLE_SAVING  = True\n',
        'ENABLE_SHOWING = False\n',
        '\n',
        'def process_videos(sources, model_path):\n',
        '    print(f"🎯 使用權重: {model_path}")\n',
        '    \n',
        '    save_dir = "偵測結果影片"\n',
        '    if not os.path.exists(save_dir): os.makedirs(save_dir)\n',
        '        \n',
        '    normalized_path = model_path.replace("\\\\", "/")\n',
        '    path_parts = normalized_path.split("/")\n',
        '    if len(path_parts) >= 3 and path_parts[-2] == "weights":\n',
        '        weight_name = f"{path_parts[-3]}_{os.path.splitext(path_parts[-1])[0]}"\n',
        '    else:\n',
        '        weight_name = os.path.splitext(path_parts[-1])[0]\n',
        '        \n',
        '    date_str = time.strftime("%Y%m%d")\n',
        '    \n',
        '    for video_source in sources:\n',
        '        model = YOLO(model_path)\n',
        '        \n',
        '        is_url = video_source.startswith("http")\n',
        '        video_name = "YouTube_Live.mp4" if is_url else os.path.basename(video_source)\n',
        '        print(f"\\n🚀 開始處理: {video_name}")\n',
        '        \n',
        '        if is_url:\n',
        '            from cap_from_youtube import cap_from_youtube\n',
        '            cap = cap_from_youtube(video_source, resolution=\'720p\')\n',
        '        else:\n',
        '            if not os.path.exists(video_source): \n',
        '                print(f"❌ 找不到檔案: {video_source}"); continue\n',
        '            cap = cv2.VideoCapture(video_source)\n',
        '\n',
        '        w, h = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))\n',
        '        fps = cap.get(cv2.CAP_PROP_FPS) or 30\n',
        '        total_f = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n',
        '        \n',
        '        out = None\n',
        '        if ENABLE_SAVING:\n',
        '            save_filename = f"{weight_name}_{date_str}_{video_name}"\n',
        '            save_path = os.path.join(save_dir, save_filename)\n',
        '            out = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*\'mp4v\'), fps/VID_STRIDE, (w, h))\n',
        '            print(f"💾 儲存路徑: {save_path}")\n',
        '\n',
        '        pbar = tqdm(total=total_f if total_f>0 else None, desc=f"Processing {video_name[:15]}")\n',
        '        frame_idx = 0\n',
        '        max_id = 0\n',
        '        \n',
        '        while cap.isOpened():\n',
        '            success, frame = cap.read()\n',
        '            if not success: break\n',
        '            \n',
        '            frame_idx += 1\n',
        '            pbar.update(1)\n',
        '            if frame_idx % VID_STRIDE != 0: continue\n',
        '\n',
        '            results = model.track(frame, persist=True, conf=CONF_THRESHOLD, iou=0.7, verbose=False)\n',
        '            \n',
        '            if results[0].boxes.id is not None:\n',
        '                curr_max = int(results[0].boxes.id.max().item())\n',
        '                if curr_max > max_id: max_id = curr_max\n',
        '            \n',
        '            annotated_frame = results[0].plot()\n',
        '            cv2.putText(annotated_frame, f"Total Strawberry IDs: {max_id}", (50, 50), \n',
        '                        cv2.FONT_HERSHEY_SIMPLEX, 1.2, (0, 255, 0), 3)\n',
        '\n',
        '            if ENABLE_SHOWING:\n',
        '                try:\n',
        '                    cv2.imshow("Strawberry Detection", annotated_frame)\n',
        '                    if cv2.waitKey(1) & 0xFF == ord(\'q\'): break\n',
        '                except (cv2.error, Exception): pass\n',
        '            \n',
        '            if out: out.write(annotated_frame)\n',
        '\n',
        '        cap.release()\n',
        '        if out: out.release()\n',
        '        pbar.close()\n',
        '        print(f"✅ {video_name} 處理完畢，最終累計 ID: {max_id}")\n',
        '\n',
        '    try:\n',
        '        cv2.destroyAllWindows()\n',
        '    except (cv2.error, Exception): pass\n',
        '\n',
        'if __name__ == "__main__":\n',
        '    print("==========================================")\n',
        '    print("🎯 YOLO 權重選擇器")\n',
        '    print("  - 可輸入編號 (如: 1c, 7) 或完整名稱 (如: exp1c_yolo11s_p2cbam)")\n',
        '    print("  - 直接按 Enter 鍵：預設取最新的實驗權重 (*)")\n',
        '    print("==========================================")\n',
        '    \n',
        '    try:\n',
        '        target_id = input("請輸入權重名稱或編號 (預設為 *): ").strip()\n',
        '    except Exception:\n',
        '        target_id = ""\n',
        '        \n',
        '    model_path = find_model_path_by_id(target_id)\n',
        '    process_videos(SOURCE_LIST, model_path=model_path)\n'
    ]

    nb['cells'][-1]['source'] = cell3_source
    with open(video_ipynb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("✅ 已成功將 影片偵測.ipynb 最後一個 cell 更新為支援互動輸入實驗編號的模式！")

def fix_eval_notebook():
    eval_ipynb_path = r"d:\銘澄專區\畢業專題工作區\模型評估與特徵視覺化.ipynb"
    if not os.path.exists(eval_ipynb_path):
        print(f"❌ 找不到目標檔案: {eval_ipynb_path}")
        return

    with open(eval_ipynb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    for cell in nb['cells']:
        if cell['cell_type'] == 'code':
            source_str = "".join(cell['source'])
            
            # 修復 Cell 3 (驗證提取混淆矩陣)
            if "2. 執行驗證並提取混淆矩陣" in source_str:
                cell['source'] = [
                    "# ==============================================================================\n",
                    "# 2. 執行驗證並提取混淆矩陣\n",
                    "# ==============================================================================\n",
                    "print(\"⏳ 正在對驗證集進行評估（可能需要數十秒，請稍候）...\")\n",
                    "\n",
                    "# 載入模型 (請確認此路徑存在)\n",
                    "MODEL_PATH = \"runs/detect/exp1a_yolo11s_baseline/weights/best.pt\"\n",
                    "DATA_YAML = \"strawberry-maturity-yolo-graduate-1/data.yaml\"\n",
                    "\n",
                    "if not os.path.exists(MODEL_PATH):\n",
                    "    raise FileNotFoundError(f\"❌ 找不到模型檔：{MODEL_PATH}，請確認訓練路徑是否正確。\")\n",
                    "\n",
                    "model = YOLO(MODEL_PATH)\n",
                    "\n",
                    "# 執行 validation，設定 workers=0 避免 Windows 下的多進程報錯，imgsz=800 與訓練對齊\n",
                    "# 必須將 plots 設為 True，YOLO 內部才會正常計算 Confusion Matrix，否則 cm_data 會全為 0\n",
                    "results = model.val(\n",
                    "    data=DATA_YAML,\n",
                    "    split=\"val\",\n",
                    "    imgsz=800,\n",
                    "    workers=0,\n",
                    "    plots=True  # 啟用繪圖以利計算混淆矩陣\n",
                    ")\n",
                    "\n",
                    "# 獲取混淆矩陣物件與數據\n",
                    "cm_obj = results.confusion_matrix\n",
                    "cm_data = cm_obj.matrix  # numpy array, shape (nc + 1, nc + 1)\n",
                    "class_names = list(model.names.values()) # ['level_1', 'level_2', 'level_3']\n",
                    "nc = len(class_names)\n",
                    "\n",
                    "# 定義具有中文註解的類別標籤\n",
                    "x_labels = class_names + ['background (漏檢)']\n",
                    "y_labels = class_names + ['background (虛警)']\n",
                    "\n",
                    "print(\"\\n✅ 混淆矩陣提取成功！\")\n",
                    "print(\"原始矩陣數據：\\n\", cm_data)\n"
                ]
                print("修復 Cell 3 完成。")
                
            # 修復 Cell 4 (繪製混淆矩陣)
            elif "3. 繪製混淆矩陣" in source_str:
                cell['source'] = [
                    "# ==============================================================================\n",
                    "# 3. 繪製混淆矩陣 (Matplotlib + Seaborn)\n",
                    "# ==============================================================================\n",
                    "# 計算 Normalized (歸一化) 混淆矩陣（依真實類別，即每一列進行歸一化）\n",
                    "cm_normalized = cm_data.copy().astype(float)\n",
                    "for i in range(nc + 1):\n",
                    "    row_sum = cm_normalized[i].sum()\n",
                    "    if row_sum > 0:\n",
                    "        cm_normalized[i] = cm_normalized[i] / row_sum\n",
                    "\n",
                    "# 建立圖表：左側展示 Raw Counts，右側展示 Normalized\n",
                    "fig, axes = plt.subplots(1, 2, figsize=(18, 7.5))\n",
                    "\n",
                    "# 3.1 繪製原始計數矩陣 (Raw Counts)\n",
                    "# 先將 cm_data 轉換成 int，避免 seaborn 對 float 在使用 fmt='d' 時報錯 ValueError\n",
                    "cm_data_int = cm_data.astype(int)\n",
                    "sns.heatmap(\n",
                    "    cm_data_int,\n",
                    "    annot=True,\n",
                    "    fmt='d',\n",
                    "    cmap='Blues',\n",
                    "    xticklabels=x_labels,\n",
                    "    yticklabels=y_labels,\n",
                    "    ax=axes[0],\n",
                    "    cbar=True,\n",
                    "    annot_kws={\"size\": 12, \"weight\": \"bold\"},\n",
                    "    linewidths=0.5,\n",
                    "    linecolor='gray'\n",
                    ")\n",
                    "axes[0].set_title(\"草莓成熟度檢測混淆矩陣 (原始計數 Raw Counts)\", fontsize=15, pad=15, weight='bold')\n",
                    "axes[0].set_xlabel(\"真實類別 (Ground Truth)\", fontsize=12, labelpad=10)\n",
                    "axes[0].set_ylabel(\"預測類別 (Predictions)\", fontsize=12, labelpad=10)\n",
                    "\n",
                    "# 3.2 繪製歸一化矩陣 (Normalized)\n",
                    "sns.heatmap(\n",
                    "    cm_normalized,\n",
                    "    annot=True,\n",
                    "    fmt='.2f',\n",
                    "    cmap='RdPu',  # 使用美麗的紅紫色調\n",
                    "    xticklabels=x_labels,\n",
                    "    yticklabels=y_labels,\n",
                    "    ax=axes[1],\n",
                    "    cbar=True,\n",
                    "    annot_kws={\"size\": 12, \"weight\": \"bold\"},\n",
                    "    linewidths=0.5,\n",
                    "    linecolor='gray'\n",
                    ")\n",
                    "axes[1].set_title(\"草莓成熟度檢測混淆矩陣 (歸一化比例 Normalized)\", fontsize=15, pad=15, weight='bold')\n",
                    "axes[1].set_xlabel(\"真實類別 (Ground Truth)\", fontsize=12, labelpad=10)\n",
                    "axes[1].set_ylabel(\"預測類別 (Predictions)\", fontsize=12, labelpad=10)\n",
                    "\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n"
                ]
                print("修復 Cell 4 完成。")
                
            # 修復 Cell 5 (YOLOGradCAM 類別定義)
            elif "class YOLOGradCAM:" in source_str:
                cell['source'] = [
                    "# ==============================================================================\n",
                    "# 4. Grad-CAM 多尺度與實體級融合核心演算法類別定義\n",
                    "# ==============================================================================\n",
                    "import torch.nn.functional as F\n",
                    "\n",
                    "def cxcywh_to_xyxy(bboxes):\n",
                    "    x_c, y_c, w, h = bboxes[0], bboxes[1], bboxes[2], bboxes[3]\n",
                    "    x1 = x_c - w / 2\n",
                    "    y1 = y_c - h / 2\n",
                    "    x2 = x_c + w / 2\n",
                    "    y2 = y_c + h / 2\n",
                    "    return torch.stack([x1, y1, x2, y2], dim=0)\n",
                    "\n",
                    "def calculate_iou(box1, box2):\n",
                    "    x1 = torch.max(box1[0], box2[0])\n",
                    "    y1 = torch.max(box1[1], box2[1])\n",
                    "    x2 = torch.min(box1[2], box2[2])\n",
                    "    y2 = torch.min(box1[3], box2[3])\n",
                    "    intersection = torch.clamp(x2 - x1, min=0) * torch.clamp(y2 - y1, min=0)\n",
                    "    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])\n",
                    "    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])\n",
                    "    union = area1 + area2 - intersection\n",
                    "    return intersection / torch.clamp(union, min=1e-6)\n",
                    "\n",
                    "class YOLOGradCAM:\n",
                    "    \"\"\"\n",
                    "    專為 YOLOv8/v11 檢測模型設計的多尺度 (Multi-scale) & 實體級 (Instance-level) Grad-CAM 實現\n",
                    "    \"\"\"\n",
                    "    def __init__(self, model):\n",
                    "        self.model = model\n",
                    "        # YOLOv11s 的 Detect 模組在第 23 層\n",
                    "        self.detect = self.model.model[23]\n",
                    "        \n",
                    "        # 取得三個尺度的類別預測特徵層 (128 channels)\n",
                    "        self.target_layers = [\n",
                    "            self.detect.cv3[0][1], # stride 8 (小目標)\n",
                    "            self.detect.cv3[1][1], # stride 16 (中目標)\n",
                    "            self.detect.cv3[2][1]  # stride 32 (大目標)\n",
                    "        ]\n",
                    "        \n",
                    "        self.activations = [None, None, None]\n",
                    "        self.gradients = [None, None, None]\n",
                    "        self.hooks = []\n",
                    "        \n",
                    "        # 註冊 hooks\n",
                    "        for i, layer in enumerate(self.target_layers):\n",
                    "            self.hooks.append(layer.register_forward_hook(self.make_save_activation(i)))\n",
                    "            self.hooks.append(layer.register_full_backward_hook(self.make_save_gradient(i)))\n",
                    "            \n",
                    "    def make_save_activation(self, idx):\n",
                    "        def save_activation(model, input, output):\n",
                    "            self.activations[idx] = output\n",
                    "        return save_activation\n",
                    "        \n",
                    "    def make_save_gradient(self, idx):\n",
                    "        def save_gradient(model, grad_input, grad_output):\n",
                    "            self.gradients[idx] = grad_output[0]\n",
                    "        return save_gradient\n",
                    "        \n",
                    "    def __call__(self, x, class_idx, instance_bbox=None, conf_threshold=0.25, iou_threshold=0.5):\n",
                    "        \"\"\"\n",
                    "        計算指定類別的 Grad-CAM\n",
                    "        x: 前處理後的圖像 Tensor, shape [1, 3, H, W]\n",
                    "        class_idx: 目標類別索引 (0: level_1, 1: level_2, 2: level_3)\n",
                    "        instance_bbox: 可選。若指定，則只針對對應檢測框的 anchors 進行反向傳播\n",
                    "        \"\"\"\n",
                    "        self.model.zero_grad()\n",
                    "        self.gradients = [None, None, None]  # 清空梯度\n",
                    "        \n",
                    "        # 執行 Forward Pass，使用 grad_enabled(True) 確保能求導\n",
                    "        with torch.set_grad_enabled(True):\n",
                    "            outputs = self.model(x)\n",
                    "        preds = outputs[0]  # shape: [1, 7, 13125]\n",
                    "        \n",
                    "        # 提取目標類別的分數\n",
                    "        class_scores = preds[0, 4 + class_idx, :]\n",
                    "        \n",
                    "        if instance_bbox is not None:\n",
                    "            # 實體級模式：計算各個 anchors 與指定 bbox 的 IoU\n",
                    "            anchor_bboxes_xyxy = cxcywh_to_xyxy(preds[0, :4, :])\n",
                    "            target_box_tensor = torch.tensor(instance_bbox, dtype=torch.float32, device=preds.device)\n",
                    "            ious = calculate_iou(anchor_bboxes_xyxy, target_box_tensor)\n",
                    "            \n",
                    "            # 篩選出 IoU >= iou_threshold 且置信度高於門檻的 anchors\n",
                    "            mask = (ious >= iou_threshold) & (class_scores > conf_threshold)\n",
                    "            num_matched = mask.sum().item()\n",
                    "            \n",
                    "            if num_matched > 0:\n",
                    "                score = class_scores[mask].sum()\n",
                    "                score.backward(retain_graph=True)\n",
                    "            else:\n",
                    "                # 備用機制：若無大於門檻的，則取 IoU 最大的那個 anchor 的 score 進行反向傳播，以自癒並防止無梯度\n",
                    "                best_idx = ious.argmax().item()\n",
                    "                score = class_scores[best_idx]\n",
                    "                score.backward(retain_graph=True)\n",
                    "        else:\n",
                    "            # 全局模式\n",
                    "            mask = class_scores > conf_threshold\n",
                    "            if mask.sum() > 0:\n",
                    "                score = class_scores[mask].sum()\n",
                    "                score.backward(retain_graph=True)\n",
                    "            else:\n",
                    "                return None, 0.0\n",
                    "            \n",
                    "        # 融合三個尺度的 CAM\n",
                    "        h_target, w_target = x.shape[2], x.shape[3]\n",
                    "        cam_total = torch.zeros((h_target, w_target), device=x.device)\n",
                    "        \n",
                    "        for i in range(3):\n",
                    "            act = self.activations[i]\n",
                    "            grad = self.gradients[i]\n",
                    "            if grad is not None and act is not None:\n",
                    "                # 對梯度進行全局平均池化 (GAP)\n",
                    "                weights = torch.mean(grad, dim=(2, 3), keepdim=True)\n",
                    "                # 將通道權重與特徵圖加權求和\n",
                    "                cam = torch.sum(weights * act, dim=1, keepdim=True)\n",
                    "                # 應用 ReLU\n",
                    "                cam = torch.clamp(cam, min=0)\n",
                    "                # 雙線性插值放大至原圖尺寸\n",
                    "                cam_resized = F.interpolate(cam, size=(h_target, w_target), mode='bilinear', align_corners=False)\n",
                    "                cam_total += cam_resized[0, 0]\n",
                    "                \n",
                    "        # 歸一化至 0 ~ 1 範圍\n",
                    "        cam_np = cam_total.cpu().detach().numpy()\n",
                    "        if cam_np.max() > 0:\n",
                    "            cam_np = cam_np / cam_np.max()\n",
                    "            \n",
                    "        return cam_np, score.item()\n",
                    "        \n",
                    "    def release(self):\n",
                    "        for hook in self.hooks:\n",
                    "            hook.remove()\n",
                    "        print(\"🔓 hooks 已成功釋放。\")\n"
                ]
                print("修復 Cell 5 完成。")
                
            # 修復 Cell 6 (run_gradcam_visualization 定義)
            elif "def run_gradcam_visualization" in source_str:
                cell['source'] = [
                    "# ==============================================================================\n",
                    "# 5. Grad-CAM 視覺化整合繪圖函數\n",
                    "# ==============================================================================\n",
                    "def run_gradcam_visualization(image_path=None, target_instance_idx=None, conf_threshold=0.25, iou_threshold=0.5):\n",
                    "    if image_path is None:\n",
                    "        valid_images = glob.glob(\"strawberry-maturity-yolo-graduate-1/valid/images/*.jpg\")\n",
                    "        if not valid_images:\n",
                    "            print(\"❌ 找不到 valid/images 目錄或裡面沒有 JPG 圖片！\")\n",
                    "            return\n",
                    "        image_path = random.choice(valid_images)\n",
                    "        \n",
                    "    print(f\"📸 處理影像路徑: {image_path}\")\n",
                    "    \n",
                    "    img_bgr = cv2.imread(image_path)\n",
                    "    if img_bgr is None:\n",
                    "        print(f\"❌ 無法讀取影像: {image_path}\")\n",
                    "        return\n",
                    "        \n",
                    "    h_org, w_org, _ = img_bgr.shape\n",
                    "    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)\n",
                    "    \n",
                    "    img_resized = cv2.resize(img_rgb, (800, 800))\n",
                    "    x_tensor = torch.from_numpy(img_resized).permute(2, 0, 1).float() / 255.0\n",
                    "    x_tensor = x_tensor.unsqueeze(0).to(device)\n",
                    "    x_tensor.requires_grad = True\n",
                    "    \n",
                    "    # 5.3 載入兩個獨立 YOLO 模型實例，避免 predict 的 inference_mode 標記權重為 Inference Tensor\n",
                    "    detector = YOLO(MODEL_PATH)\n",
                    "    results = detector.predict(image_path, conf=conf_threshold, imgsz=800, verbose=False)[0]\n",
                    "    \n",
                    "    temp_model = YOLO(MODEL_PATH)\n",
                    "    py_model = temp_model.model.to(device)\n",
                    "    py_model.eval()\n",
                    "    \n",
                    "    # 5.4 建立 Grad-CAM 實例\n",
                    "    grad_cam = YOLOGradCAM(py_model)\n",
                    "    \n",
                    "    classes_zh = ['第一級 level_1 (未成熟/青綠色)', \n",
                    "                  '第二級 level_2 (半熟/粉紅色)', \n",
                    "                  '第三級 level_3 (完全成熟/鮮紅色)']\n",
                    "                  \n",
                    "    # 5.5 判斷模式與繪圖排版\n",
                    "    if target_instance_idx is not None:\n",
                    "        if len(results.boxes) == 0:\n",
                    "            print(\"⚠️ 影像中沒有偵測到任何目標，自動切換至全圖模式。\")\n",
                    "            target_instance_idx = None\n",
                    "        elif target_instance_idx >= len(results.boxes):\n",
                    "            print(f\"⚠️ 指定實體索引 [{target_instance_idx}] 溢位，自動切換至實體 [0]。\")\n",
                    "            target_instance_idx = 0\n",
                    "            \n",
                    "    if target_instance_idx is not None:\n",
                    "        # 實體級模式繪圖 (2x2 排版)\n",
                    "        fig, axes = plt.subplots(2, 2, figsize=(14, 12))\n",
                    "        axes = axes.ravel()\n",
                    "        \n",
                    "        box = results.boxes[target_instance_idx]\n",
                    "        cls_idx = int(box.cls.item())\n",
                    "        xyxy = box.xyxy[0].cpu().numpy()\n",
                    "        \n",
                    "        # 1. 繪製原圖加框\n",
                    "        img_annotate = img_rgb.copy()\n",
                    "        for j, b in enumerate(results.boxes):\n",
                    "            b_xyxy = b.xyxy[0].cpu().numpy().astype(int)\n",
                    "            b_cls = int(b.cls.item())\n",
                    "            b_conf = b.conf.item()\n",
                    "            color = (0, 255, 0) if j == target_instance_idx else (255, 0, 0)\n",
                    "            thickness = 3 if j == target_instance_idx else 1\n",
                    "            cv2.rectangle(img_annotate, (b_xyxy[0], b_xyxy[1]), (b_xyxy[2], b_xyxy[3]), color, thickness)\n",
                    "            cv2.putText(img_annotate, f'[{j}] L{b_cls+1} {b_conf:.2f}', (b_xyxy[0], b_xyxy[1]-10),\n",
                    "                        cv2.FONT_HERSHEY_SIMPLEX, 0.65, color, 2)\n",
                    "                        \n",
                    "        axes[0].imshow(img_annotate)\n",
                    "        axes[0].set_title(f'原始影像 (標註偵測目標，綠色 [{target_instance_idx}] 為被解釋個體)', fontsize=12, weight='bold')\n",
                    "        axes[0].axis('off')\n",
                    "        \n",
                    "        # 2. 計算實體級 Grad-CAM\n",
                    "        xyxy_800 = [\n",
                    "            xyxy[0] * 800.0 / w_org,\n",
                    "            xyxy[1] * 800.0 / h_org,\n",
                    "            xyxy[2] * 800.0 / w_org,\n",
                    "            xyxy[3] * 800.0 / h_org\n",
                    "        ]\n",
                    "        cam_inst, score_inst = grad_cam(x_tensor, cls_idx, instance_bbox=xyxy_800, conf_threshold=conf_threshold, iou_threshold=iou_threshold)\n",
                    "        if cam_inst is not None:\n",
                    "            cam_inst_resized = cv2.resize(cam_inst, (w_org, h_org))\n",
                    "            heatmap_inst = cv2.applyColorMap(np.uint8(255 * cam_inst_resized), cv2.COLORMAP_JET)\n",
                    "            heatmap_inst = cv2.cvtColor(heatmap_inst, cv2.COLOR_BGR2RGB)\n",
                    "            overlay_inst = cv2.addWeighted(img_rgb, 0.6, heatmap_inst, 0.4, 0)\n",
                    "            cv2.rectangle(overlay_inst, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0, 255, 0), 3)\n",
                    "            axes[1].imshow(overlay_inst)\n",
                    "            axes[1].set_title(f'指定實體 [{target_instance_idx}] ({classes_zh[cls_idx]}) 特徵聚焦 Grad-CAM\\n(個體回應強度 Score: {score_inst:.4f})', fontsize=12, weight='bold')\n",
                    "        else:\n",
                    "            axes[1].imshow(img_rgb)\n",
                    "            axes[1].set_title(f'實體 [{target_instance_idx}] Grad-CAM (無回應)', fontsize=12, color='gray')\n",
                    "        axes[1].axis('off')\n",
                    "        \n",
                    "        # 3. 計算全圖同類別對照組\n",
                    "        cam_global, score_global = grad_cam(x_tensor, cls_idx, instance_bbox=None, conf_threshold=conf_threshold)\n",
                    "        if cam_global is not None:\n",
                    "            cam_global_resized = cv2.resize(cam_global, (w_org, h_org))\n",
                    "            heatmap_global = cv2.applyColorMap(np.uint8(255 * cam_global_resized), cv2.COLORMAP_JET)\n",
                    "            heatmap_global = cv2.cvtColor(heatmap_global, cv2.COLOR_BGR2RGB)\n",
                    "            overlay_global = cv2.addWeighted(img_rgb, 0.6, heatmap_global, 0.4, 0)\n",
                    "            cv2.rectangle(overlay_global, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (255, 255, 0), 2)\n",
                    "            axes[2].imshow(overlay_global)\n",
                    "            axes[2].set_title(f'全圖同成熟度類別對照 (Global CAM)\\n(全圖回應強度 Score: {score_global:.4f})', fontsize=12, weight='bold')\n",
                    "        else:\n",
                    "            axes[2].imshow(img_rgb)\n",
                    "            axes[2].set_title(\"全圖同成熟度對照 (無回應)\", fontsize=12, color='gray')\n",
                    "        axes[2].axis('off')\n",
                    "        \n",
                    "        # 4. 繪製其他非目標成熟度類別的 Global CAM 以利對比\n",
                    "        other_cls = (cls_idx + 1) % 3\n",
                    "        cam_other, score_other = grad_cam(x_tensor, other_cls, instance_bbox=None, conf_threshold=conf_threshold)\n",
                    "        if cam_other is not None:\n",
                    "            cam_other_resized = cv2.resize(cam_other, (w_org, h_org))\n",
                    "            heatmap_other = cv2.applyColorMap(np.uint8(255 * cam_other_resized), cv2.COLORMAP_JET)\n",
                    "            heatmap_other = cv2.cvtColor(heatmap_other, cv2.COLOR_BGR2RGB)\n",
                    "            overlay_other = cv2.addWeighted(img_rgb, 0.6, heatmap_other, 0.4, 0)\n",
                    "            axes[3].imshow(overlay_other)\n",
                    "            axes[3].set_title(f'其他成熟度類別對照: {classes_zh[other_cls]}\\n(全圖回應強度 Score: {score_other:.4f})', fontsize=12, weight='bold')\n",
                    "        else:\n",
                    "            gray_img = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)\n",
                    "            gray_img_3ch = cv2.merge([gray_img, gray_img, gray_img])\n",
                    "            faded = cv2.addWeighted(img_rgb, 0.3, gray_img_3ch, 0.7, 0)\n",
                    "            axes[3].imshow(faded)\n",
                    "            axes[3].set_title(f'其他成熟度對照: {classes_zh[other_cls]} (無偵測目標)', fontsize=12, color='gray')\n",
                    "            axes[3].text(w_org // 2, h_org // 2, '此成熟度級別未檢測到目標', color='yellow', fontsize=12, weight='bold',\n",
                    "                         horizontalalignment='center', verticalalignment='center',\n",
                    "                         bbox=dict(facecolor='black', alpha=0.6, boxstyle='round,pad=0.4'))\n",
                    "        axes[3].axis('off')\n",
                    "        \n",
                    "        save_mode_str = f'instance{target_instance_idx}'\n",
                    "    else:\n",
                    "        # 全局模式繪圖\n",
                    "        fig, axes = plt.subplots(2, 2, figsize=(14, 12))\n",
                    "        axes = axes.ravel()\n",
                    "        \n",
                    "        axes[0].imshow(img_rgb)\n",
                    "        axes[0].set_title(f'原始影像 ({os.path.basename(image_path)})', fontsize=12, weight='bold')\n",
                    "        axes[0].axis('off')\n",
                    "        \n",
                    "        for i, cls_name in enumerate(classes_zh):\n",
                    "            cam, score = grad_cam(x_tensor, i, conf_threshold=conf_threshold)\n",
                    "            if cam is not None:\n",
                    "                cam_resized = cv2.resize(cam, (w_org, h_org))\n",
                    "                heatmap = cv2.applyColorMap(np.uint8(255 * cam_resized), cv2.COLORMAP_JET)\n",
                    "                heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)\n",
                    "                overlay = cv2.addWeighted(img_rgb, 0.6, heatmap, 0.4, 0)\n",
                    "                axes[i+1].imshow(overlay)\n",
                    "                axes[i+1].set_title(f'{cls_name}\\n(模型回應強度 Score: {score:.4f})', fontsize=12, pad=10, weight='bold')\n",
                    "            else:\n",
                    "                gray_img = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)\n",
                    "                gray_img_3ch = cv2.merge([gray_img, gray_img, gray_img])\n",
                    "                faded = cv2.addWeighted(img_rgb, 0.3, gray_img_3ch, 0.7, 0)\n",
                    "                axes[i+1].imshow(faded)\n",
                    "                axes[i+1].set_title(f'{cls_name}\\n(無檢測到此成熟度目標)', fontsize=12, pad=10, color='gray', style='italic')\n",
                    "                axes[i+1].text(w_org // 2, h_org // 2, '此成熟度級別未檢測到目標', \n",
                    "                               color='yellow', fontsize=14, weight='bold', \n",
                    "                               horizontalalignment='center', verticalalignment='center',\n",
                    "                               bbox=dict(facecolor='black', alpha=0.6, boxstyle='round,pad=0.5'))\n",
                    "            axes[i+1].axis('off')\n",
                    "            \n",
                    "        save_mode_str = 'global'\n",
                    "        \n",
                    "    plt.tight_layout()\n",
                    "    \n",
                    "    # --- create model-named subfolder ---\n",
                    "    model_dir_name = os.path.basename(os.path.dirname(os.path.dirname(MODEL_PATH)))\n",
                    "    save_dir = os.path.join('evaluation_results', model_dir_name)\n",
                    "    os.makedirs(save_dir, exist_ok=True)\n",
                    "    img_basename = os.path.splitext(os.path.basename(image_path))[0]\n",
                    "    conf_tag = f'conf{int(conf_threshold*100):02d}'\n",
                    "    iou_tag  = f'iou{int(iou_threshold*100):02d}'\n",
                    "    save_path = os.path.join(save_dir, f'gradcam_{model_dir_name}_{img_basename}_{save_mode_str}_{conf_tag}_{iou_tag}.png')\n",
                    "    plt.savefig(save_path, dpi=150, bbox_inches='tight')\n",
                    "    print(f\"💾 Grad-CAM 特徵圖已成功儲存至: {save_path}\")\n",
                    "    plt.show()\n",
                    "    \n",
                    "    grad_cam.release()\n"
                ]
                print("修復 Cell 6 完成。")
                
            # 修復 Cell 7a — 批次執行視覺化（識別碼：import random + 批次迴圈）
            elif "import random" in source_str and "run_gradcam_visualization(" in source_str:
                cell['source'] = [
                    "# ==============================================================================\n",
                    "# 6. 批次執行視覺化 (自動生成全圖與單一實體對照的 Grad-CAM 成果圖並保存)\n",
                    "# ==============================================================================\n",
                    "import random\n",
                    "valid_images = glob.glob(\"strawberry-maturity-yolo-graduate-1/valid/images/*.jpg\")\n",
                    "if valid_images:\n",
                    "    print(\"⏳ 正在對驗證集進行篩選，以獲取適合論文插圖的影像...\")\n",
                    "    detector = YOLO(MODEL_PATH)\n",
                    "    multi_strawberries_imgs = []\n",
                    "    single_strawberry_imgs = []\n",
                    "    \n",
                    "    random.shuffle(valid_images)\n",
                    "    for img_path in valid_images:\n",
                    "        res = detector.predict(img_path, conf=0.25, verbose=False)[0]\n",
                    "        if len(res.boxes) >= 2:\n",
                    "            multi_strawberries_imgs.append(img_path)\n",
                    "            if len(multi_strawberries_imgs) >= 5:\n",
                    "                break\n",
                    "        elif len(res.boxes) == 1:\n",
                    "            single_strawberry_imgs.append(img_path)\n",
                    "            \n",
                    "    selected_imgs = multi_strawberries_imgs[:5]\n",
                    "    needed = 10 - len(selected_imgs)\n",
                    "    selected_imgs.extend(single_strawberry_imgs[:needed])\n",
                    "    if len(selected_imgs) < 10:\n",
                    "        remaining = [img for img in valid_images if img not in selected_imgs]\n",
                    "        selected_imgs.extend(remaining[:10 - len(selected_imgs)])\n",
                    "        \n",
                    "    print(f\"🚀 開始批次生成並保存 {len(selected_imgs)} 張影像的多尺度/實體級 Grad-CAM 特徵圖...\")\n",
                    "    for i, img_path in enumerate(selected_imgs):\n",
                    "        if i < 5:\n",
                    "            run_gradcam_visualization(image_path=img_path, target_instance_idx=0, conf_threshold=0.25)\n",
                    "        else:\n",
                    "            run_gradcam_visualization(image_path=img_path, target_instance_idx=None, conf_threshold=0.25)\n",
                    "    print(\"\\n🎉 批次生成完成！所有結果已保存在 evaluation_results/ 資料夾中，可用於論文挑選。\")\n",
                    "else:\n",
                    "    print(\"❌ 找不到 valid/images 目錄或裡面沒有 JPG 圖片！\")\n"
                ]
                print("修復 Cell 7a（批次）完成。")

            # 修復 Cell 7b — 自訂單張影像互動測試（識別碼：CUSTOM_IMG_PATH）
            elif "CUSTOM_IMG_PATH" in source_str or (
                "run_gradcam_visualization(" in source_str and "import random" not in source_str
            ):
                cell['source'] = [
                    "# ==============================================================================\n",
                    "# 🎯 自訂單張影像 Grad-CAM 視覺化與分析（參數調整測試用）\n",
                    "# ==============================================================================\n",
                    "import os\n",
                    "\n",
                    "# 1. 填寫您想測試的草莓影像路徑（支援相對路徑或 Windows 絕對路徑）\n",
                    "CUSTOM_IMG_PATH = r\"strawberry-maturity-yolo-graduate-1\\valid\\images\\1008_jpg.rf.2ebf5cb716779583008f6f72d36a633c.jpg\"\n",
                    "\n",
                    "# 2. 設定解釋模式\n",
                    "# - 若設為數字 (如 0, 1, 2)：會啟動「單一實體級 Grad-CAM」，聚焦在指定編號的草莓上\n",
                    "# - 若設為 None          ：會啟動「全圖模式」，展示整張影像上的特徵分佈\n",
                    "TARGET_INSTANCE = None\n",
                    "\n",
                    "# 3. 執行視覺化 (可自訂置信度與 IoU 匹配門檻)\n",
                    "if os.path.exists(CUSTOM_IMG_PATH):\n",
                    "    run_gradcam_visualization(\n",
                    "        image_path=CUSTOM_IMG_PATH,\n",
                    "        target_instance_idx=TARGET_INSTANCE,\n",
                    "        conf_threshold=0.25,\n",
                    "        iou_threshold=0.50,\n",
                    "    )\n",
                    "else:\n",
                    "    print(f\"❌ 找不到指定的影像檔案，請確認路徑是否正確：{CUSTOM_IMG_PATH}\")\n"
                ]
                print("修復 Cell 7b（自訂路徑）完成。")

    # --- 最後一個 Cell 永遠強制設為自訂路徑測試 Cell（完全獨立，不依賴前面 Cell）---
    nb['cells'][-1]['source'] = [
        "# ==============================================================================\n",
        "# 🎯 自訂單張影像 Grad-CAM 視覺化與分析（參數調整測試用）\n",
        "# 本 Cell 可單獨執行，無需先執行前面的 Cell。\n",
        "# ==============================================================================\n",
        "import sys, os\n",
        "\n",
        "# --- 自動將 agent_tools 加入模組搜尋路徑 ---\n",
        "if 'agent_tools' not in sys.path[0]:\n",
        "    sys.path.insert(0, os.getcwd())\n",
        "\n",
        "from agent_tools.gradcam_utils import run_gradcam_visualization\n",
        "\n",
        "# 若前面 Cell 沒跑，自動補齊 MODEL_PATH\n",
        "try:\n",
        "    MODEL_PATH\n",
        "except NameError:\n",
        "    MODEL_PATH = \"runs/detect/exp1a_yolo11s_baseline/weights/best.pt\"\n",
        "\n",
        "import agent_tools.gradcam_utils as _gu\n",
        "_gu.MODEL_PATH = MODEL_PATH\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 1. 填寫您想測試的草莓影像路徑\n",
        "#    加上 r 後，反斜線不會被轉義\n",
        "CUSTOM_IMG_PATH = r\"strawberry-maturity-yolo-graduate-1\\valid\\images\\1008_jpg.rf.2ebf5cb716779583008f6f72d36a633c.jpg\"\n",
        "\n",
        "# 2. 設定解釋模式\n",
        "#    - 數字 (如 0, 1, 2)：單一實體級 Grad-CAM，聚焦在指定編號的草莓\n",
        "#    - None             ：全圖模式，展示三種成熟度的特徵分佈\n",
        "TARGET_INSTANCE = None\n",
        "\n",
        "# 3. 執行視覺化（可自訂 conf / iou 門檻）\n",
        "#    輸出路徑：evaluation_results/<模型名>/<檔名>_<模式>_conf<n>_iou<n>.png\n",
        "if os.path.exists(CUSTOM_IMG_PATH):\n",
        "    run_gradcam_visualization(\n",
        "        image_path=CUSTOM_IMG_PATH,\n",
        "        target_instance_idx=TARGET_INSTANCE,\n",
        "        conf_threshold=0.25,\n",
        "        iou_threshold=0.50,\n",
        "    )\n",
        "else:\n",
        "    print(f\"❌ 找不到指定的影像檔案，請確認路徑是否正確：{CUSTOM_IMG_PATH}\")\n",
    ]
    print("✅ Cell 10（自訂路徑，獨立模式）已強制還原。")

    with open(eval_ipynb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("✅ 已成功完成 模型評估與特徵視覺化.ipynb 所有 Cells 的程式碼修復！")

if __name__ == "__main__":
    update_notebook()
    fix_video_detection_notebook()
    fix_eval_notebook()
