import json
import os
import sys

# Reconfigure stdout to use utf-8 to avoid Big5 (cp950) encoding errors with emojis like 🍓, ✅, etc.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

"""
🛠️ Notebook 批量修復/更新工具 (Agent 專用)
---
用途：用於修復 讀取訓練結果.ipynb 的 StdinNotImplementedError 與 pkg_resources 缺失問題。
"""

ipynb_path = r"d:\銘澄專區\畢業專題工作區\讀取訓練結果.ipynb"

cell4_source = [
    "#監控訓練中的最新結果\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "import time\n",
    "import glob\n",
    "import threading\n",
    "from IPython.display import clear_output, display\n",
    "\n",
    "# 旗標：控制背景監控是否繼續\n",
    "keep_running = True\n",
    "\n",
    "def get_latest_results_csv(base_path=\"Strawberry_YOLOv11_4060ti-16G/*/results.csv\"):\n",
    "    files = glob.glob(base_path)\n",
    "    if not files: return None\n",
    "    return max(files, key=os.path.getmtime)\n",
    "\n",
    "def plot_training_results():\n",
    "    csv_path = get_latest_results_csv()\n",
    "    if csv_path is None or not os.path.exists(csv_path):\n",
    "        print(f\"⌛ 等待訓練數據產生中...\")\n",
    "        return\n",
    "\n",
    "    try:\n",
    "        df = pd.read_csv(csv_path)\n",
    "        df.columns = [c.strip() for c in df.columns]\n",
    "    except: return\n",
    "\n",
    "    if df.empty: return\n",
    "\n",
    "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "    # --- Loss 圖 ---\n",
    "    ax1.plot(df['epoch'], df['train/box_loss'], label='Train Box', color='blue', alpha=0.4)\n",
    "    ax1.plot(df['epoch'], df['val/box_loss'], label='Val Box', color='blue', linestyle='--')\n",
    "    ax1.plot(df['epoch'], df['train/cls_loss'], label='Train Cls', color='orange', alpha=0.4)\n",
    "    ax1.plot(df['epoch'], df['val/cls_loss'], label='Val Cls', color='orange', linestyle='--')\n",
    "    ax1.set_title(f\"Loss Curves ({os.path.basename(os.path.dirname(csv_path))})\")\n",
    "    ax1.legend(); ax1.grid(True)\n",
    "\n",
    "    # --- mAP 圖 ---\n",
    "    ax2.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP50', color='green', linewidth=2)\n",
    "    ax2.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP50-95', color='red', linewidth=1)\n",
    "    ax2.set_title(\"mAP Metrics\")\n",
    "    ax2.legend(); ax2.grid(True)\n",
    "\n",
    "    clear_output(wait=True)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    print(f\"📊 最新更新時間: {time.strftime('%Y-%m-%d %H:%M:%S')} | 數據源: {csv_path}\")\n",
    "\n",
    "def monitor_loop(interval=10):\n",
    "    while keep_running:\n",
    "        plot_training_results()\n",
    "        time.sleep(interval)\n",
    "\n",
    "# 啟動背景監控執行緒\n",
    "monitor_thread = threading.Thread(target=monitor_loop, args=(10,), daemon=True)\n",
    "monitor_thread.start()\n",
    "print(\"🟢 已經在背景啟動訓練結果即時監控！每一輪(Epoch)結束後圖表將會自動重繪。\")\n"
]

cell6_source = [
    "import sys\n",
    "sys.argv = [sys.argv[0]]\n",
    "import nvidia_ml_py as pynvml\n",
    "import torch\n",
    "\n",
    "def safe_decode(val):\n",
    "    if isinstance(val, bytes): return val.decode('utf-8', errors='ignore')\n",
    "    return str(val)\n",
    "\n",
    "def get_gpu_health_check():\n",
    "    print(\"========================================================================\")\n",
    "    print(\"🚀 RTX 4060 Ti (16G) GPU 健檢程式 - 鎖定 pytorch 核心環境與 nvidia-ml-py 驅動\")\n",
    "    print(\"========================================================================\")\n",
    "    \n",
    "    # 1. 檢查 PyTorch CUDA 可用度\n",
    "    cuda_available = torch.cuda.is_available()\n",
    "    print(f\"🔹 PyTorch CUDA 可用狀態: {cuda_available}\")\n",
    "    if cuda_available:\n",
    "        print(f\"   - 顯示卡型號       : {torch.cuda.get_device_name(0)}\")\n",
    "        print(f\"   - CUDA 驅動版本    : {torch.version.cuda}\")\n",
    "        print(f\"   - PyTorch 核心版本 : {torch.__version__}\")\n",
    "    else:\n",
    "        print(\"   ❌ PyTorch 無法辨識 GPU，請檢查 CUDA / PyTorch 版本對齊狀態！\")\n",
    "        return\n",
    "        \n",
    "    # 2. 透過 nvidia-ml-py 初始化並提取精確物理硬體數據\n",
    "    print(\"\\n🔹 nvidia-ml-py (NVML) 硬體即時數據診斷:\")\n",
    "    try:\n",
    "        pynvml.nvmlInit()\n",
    "        handle = pynvml.nvmlDeviceGetHandleByIndex(0)\n",
    "        \n",
    "        # 取得各種資訊\n",
    "        gpu_name = safe_decode(pynvml.nvmlDeviceGetName(handle))\n",
    "        driver_ver = safe_decode(pynvml.nvmlSystemGetDriverVersion())\n",
    "        mem_info = pynvml.nvmlDeviceGetMemoryInfo(handle)\n",
    "        \n",
    "        # 時脈與頻寬相關\n",
    "        curr_graphics_clock = pynvml.nvmlDeviceGetClockInfo(handle, pynvml.NVML_CLOCK_GRAPHICS)\n",
    "        curr_mem_clock = pynvml.nvmlDeviceGetClockInfo(handle, pynvml.NVML_CLOCK_MEM)\n",
    "        max_graphics_clock = pynvml.nvmlDeviceGetMaxClockInfo(handle, pynvml.NVML_CLOCK_GRAPHICS)\n",
    "        \n",
    "        # 溫度與電力\n",
    "        temp = pynvml.nvmlDeviceGetTemperature(handle, pynvml.NVML_TEMPERATURE_GPU)\n",
    "        power_usage = pynvml.nvmlDeviceGetPowerUsage(handle) / 1000.0 # 轉為 W\n",
    "        power_limit = pynvml.nvmlDeviceGetPowerManagementLimit(handle) / 1000.0\n",
    "\n",
    "        print(f\"   - 正式名稱       : {gpu_name}\")\n",
    "        print(f\"   - 驅動程式版本   : {driver_ver}\")\n",
    "        print(f\"   - 總顯存 (VRAM)  : {mem_info.total / 1024**2:.0f} MB\")\n",
    "        print(f\"   - 目前顯存佔用   : {mem_info.used / 1024**2:.0f} MB ({(mem_info.used/mem_info.total)*100:.1f}%)\")\n",
    "        print(f\"   - 核心時脈       : {curr_graphics_clock} MHz (Max: {max_graphics_clock} MHz)\")\n",
    "        print(f\"   - 記憶體時脈     : {curr_mem_clock} MHz\")\n",
    "        print(f\"   - 當前溫度       : {temp} °C\")\n",
    "        print(f\"   - 當前功耗       : {power_usage:.1f} W / {power_limit:.1f} W\")\n",
    "        \n",
    "        # 計算理論頻寬\n",
    "        pcie_gen = pynvml.nvmlDeviceGetMaxPcieLinkGeneration(handle)\n",
    "        pcie_width = pynvml.nvmlDeviceGetMaxPcieLinkWidth(handle)\n",
    "        print(f\"   - PCIe 介面      : Gen {pcie_gen} x{pcie_width}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"   ❌ NVML 診斷失敗: {e}\")\n",
    "    finally:\n",
    "        try: pynvml.nvmlShutdown()\n",
    "        except: pass\n",
    "\n",
    "    print(f\"\\n{'='*80}\")\n",
    "    print(\"✅ 健檢完成！目前環境與 RTX 4060 Ti 處於最佳狀態。\")\n",
    "\n",
    "get_gpu_health_check()\n"
]

def update_notebook():
    if not os.path.exists(ipynb_path):
        print(f"❌ 找不到目標檔案: {ipynb_path}")
        return

    with open(ipynb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # 修復監控 Cell (index 4) 與 GPU 健檢 Cell (index 6)
    nb['cells'][4]['source'] = cell4_source
    nb['cells'][6]['source'] = cell6_source

    with open(ipynb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    
    print(f"✅ 已成功更新 讀取訓練結果.ipynb 中的 Cell 4 與 Cell 6。")

def fix_video_detection_notebook():
    video_ipynb_path = r"d:\銘澄專區\畢業專題工作區\影片偵測.ipynb"
    if not os.path.exists(video_ipynb_path):
        print(f"❌ 找不到目標檔案: {video_ipynb_path}")
        return

    with open(video_ipynb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # 最後一個 Cell 的新完整程式碼
    cell3_source = [
        'import sys\n',
        'sys.argv = [sys.argv[0]]\n',
        'import os, glob, cv2, time\n',
        'import numpy as np\n',
        'from ultralytics import YOLO\n',
        'from tqdm.notebook import tqdm\n',
        'from collections import defaultdict\n',
        '\n',
        'def find_model_path_by_id(target_id="", base_dir="runs/detect"):\n',
        '    """\n',
        '    從輸入編號 (如 1c, 7) 自動搜尋匹配的權重檔案路徑，預設/為空時取最新 (*)\n',
        '    """\n',
        '    # 1. 如果輸入是空字串或 \'*\', 自動尋找最新的\n',
        '    if not target_id or target_id == \'*\':\n',
        '        search_patterns = [os.path.join(base_dir, \'train*\'), os.path.join(base_dir, \'exp*\')]\n',
        '        dirs = []\n',
        '        for pattern in search_patterns: dirs.extend(glob.glob(pattern))\n',
        '        valid_dirs = [d for d in dirs if os.path.exists(os.path.join(d, \'weights\', \'best.pt\'))]\n',
        '        if valid_dirs:\n',
        '            latest_dir = max(valid_dirs, key=os.path.getmtime)\n',
        '            return os.path.join(latest_dir, \'weights\', \'best.pt\')\n',
        '        weights = glob.glob(os.path.join(\'best_weights\', \'*.pt\'))\n',
        '        return max(weights, key=os.path.getmtime) if weights else \'yolov11n.pt\'\n',
        '        \n',
        '    # 2. 如果輸入了特定 ID (例如 \'1c\', \'7\', \'exp1c\', \'train7\')\n',
        '    search_patterns = [os.path.join(base_dir, \'train*\'), os.path.join(base_dir, \'exp*\')]\n',
        '    dirs = []\n',
        '    for pattern in search_patterns: dirs.extend(glob.glob(pattern))\n',
        '    \n',
        '    matched_dirs = []\n',
        '    for d in dirs:\n',
        '        folder_name = os.path.basename(d).lower()\n',
        '        if target_id.lower() in folder_name and os.path.exists(os.path.join(d, \'weights\', \'best.pt\')):\n',
        '            matched_dirs.append(d)\n',
        '            \n',
        '    if matched_dirs:\n',
        '        best_match = max(matched_dirs, key=os.path.getmtime)\n',
        '        return os.path.join(best_match, \'weights\', \'best.pt\')\n',
        '        \n',
        '    # 3. 嘗試在 best_weights 下搜尋\n',
        '    best_weights_dir = \'best_weights\'\n',
        '    if os.path.exists(best_weights_dir):\n',
        '        weights = glob.glob(os.path.join(best_weights_dir, \'*.pt\'))\n',
        '        matched_weights = [w for w in weights if target_id.lower() in os.path.basename(w).lower()]\n',
        '        if matched_weights:\n',
        '            return max(matched_weights, key=os.path.getmtime)\n',
        '            \n',
        '    # 4. 如果是直接輸入了存在的文件路徑\n',
        '    if os.path.exists(target_id): return target_id\n',
        '        \n',
        '    print(f"⚠️ 找不到匹配編號 \'{target_id}\' 的權重檔，將自動切換為最新模型 (*)")\n',
        '    return find_model_path_by_id(\'*\', base_dir)\n',
        '\n',
        '# ==========================================\n',
        '# 🎬 影片偵測核心 (支援單部 / 批量 / 獨立 ID)\n',
        '# ==========================================\n',
        '\n',
        '# 1. 任務設定\n',
        'SOURCE_LIST = [\n',
        '    "測試模型用/模擬_4(無聲音).mp4",\n',
        ']\n',
        '\n',
        '# 2. 功能開關\n',
        'VID_STRIDE     = 1\n',
        'CONF_THRESHOLD = 0.5\n',
        'ENABLE_SAVING  = True\n',
        'ENABLE_SHOWING = False\n',
        '\n',
        'def process_videos(sources, model_path):\n',
        '    print(f"🎯 使用權重: {model_path}")\n',
        '    \n',
        '    save_dir = "偵測結果影片"\n',
        '    if not os.path.exists(save_dir): os.makedirs(save_dir)\n',
        '        \n',
        '    # 提取更具識別度的權重名稱\n',
        '    normalized_path = model_path.replace("\\\\", "/")\n',
        '    path_parts = normalized_path.split("/")\n',
        '    if len(path_parts) >= 3 and path_parts[-2] == "weights":\n',
        '        weight_name = f"{path_parts[-3]}_{os.path.splitext(path_parts[-1])[0]}"\n',
        '    else:\n',
        '        weight_name = os.path.splitext(path_parts[-1])[0]\n',
        '        \n',
        '    date_str = time.strftime("%Y%m%d")\n',
        '    \n',
        '    for video_source in sources:\n',
        '        model = YOLO(model_path)\n',
        '        \n',
        '        is_url = video_source.startswith("http")\n',
        '        video_name = "YouTube_Live.mp4" if is_url else os.path.basename(video_source)\n',
        '        print(f"\\n🚀 開始處理: {video_name}")\n',
        '        \n',
        '        if is_url:\n',
        '            from cap_from_youtube import cap_from_youtube\n',
        '            cap = cap_from_youtube(video_source, resolution=\'720p\')\n',
        '        else:\n',
        '            if not os.path.exists(video_source): \n',
        '                print(f"❌ 找不到檔案: {video_source}"); continue\n',
        '            cap = cv2.VideoCapture(video_source)\n',
        '\n',
        '        w, h = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))\n',
        '        fps = cap.get(cv2.CAP_PROP_FPS) or 30\n',
        '        total_f = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n',
        '        \n',
        '        out = None\n',
        '        if ENABLE_SAVING:\n',
        '            save_filename = f"{weight_name}_{date_str}_{video_name}"\n',
        '            save_path = os.path.join(save_dir, save_filename)\n',
        '            out = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*\'mp4v\'), fps/VID_STRIDE, (w, h))\n',
        '            print(f"💾 儲存路徑: {save_path}")\n',
        '\n',
        '        pbar = tqdm(total=total_f if total_f>0 else None, desc=f"Processing {video_name[:15]}")\n',
        '        frame_idx = 0\n',
        '        max_id = 0\n',
        '        \n',
        '        while cap.isOpened():\n',
        '            success, frame = cap.read()\n',
        '            if not success: break\n',
        '            \n',
        '            frame_idx += 1\n',
        '            pbar.update(1)\n',
        '            if frame_idx % VID_STRIDE != 0: continue\n',
        '\n',
        '            results = model.track(frame, persist=True, conf=CONF_THRESHOLD, iou=0.7, verbose=False)\n',
        '            \n',
        '            if results[0].boxes.id is not None:\n',
        '                curr_max = int(results[0].boxes.id.max().item())\n',
        '                if curr_max > max_id: max_id = curr_max\n',
        '            \n',
        '            annotated_frame = results[0].plot()\n',
        '            cv2.putText(annotated_frame, f"Total Strawberry IDs: {max_id}", (50, 50), \n',
        '                        cv2.FONT_HERSHEY_SIMPLEX, 1.2, (0, 255, 0), 3)\n',
        '\n',
        '            if ENABLE_SHOWING:\n',
        '                try:\n',
        '                    cv2.imshow("Strawberry Detection", annotated_frame)\n',
        '                    if cv2.waitKey(1) & 0xFF == ord(\'q\'): break\n',
        '                except (cv2.error, Exception): pass\n',
        '            \n',
        '            if out: out.write(annotated_frame)\n',
        '\n',
        '        cap.release()\n',
        '        if out: out.release()\n',
        '        pbar.close()\n',
        '        print(f"✅ {video_name} 處理完畢，最終累計 ID: {max_id}")\n',
        '\n',
        '    try:\n',
        '        cv2.destroyAllWindows()\n',
        '    except (cv2.error, Exception): pass\n',
        '\n',
        'if __name__ == "__main__":\n',
        '    print("==========================================")\n',
        '    print("🎯 YOLO 權重選擇器")\n',
        '    print("  - 可輸入編號 (如: 1c, 7) 或完整名稱 (如: exp1c_yolo11s_p2cbam)")\n',
        '    print("  - 直接按 Enter 鍵：預設取最新的實驗權重 (*)")\n',
        '    print("==========================================")\n',
        '    \n',
        '    try:\n',
        '        target_id = input("請輸入權重名稱或編號 (預設為 *): ").strip()\n',
        '    except Exception:\n',
        '        target_id = ""\n',
        '        \n',
        '    model_path = find_model_path_by_id(target_id)\n',
        '    process_videos(SOURCE_LIST, model_path=model_path)\n'
    ]

    nb['cells'][-1]['source'] = cell3_source
    with open(video_ipynb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("✅ 已成功將 影片偵測.ipynb 最後一個 cell 更新為支援互動輸入實驗編號的模式！")

if __name__ == "__main__":
    update_notebook()
    fix_video_detection_notebook()
